name: "ğŸ“ Issue Template"
description: "ëª¨ë“  ìœ í˜•ì— ì‚¬ìš©í•  ìˆ˜ ìˆëŠ” ê³µí†µ ì´ìŠˆ í…œí”Œë¦¿"
title: ""
labels: []
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "ğŸ“Œ ì´ìŠˆ ìœ í˜•"
      description: "ì´ ì´ìŠˆê°€ ì–´ë–¤ ìœ í˜•ì¸ì§€ ì„ íƒí•˜ì„¸ìš”."
      options:
        - "Feature"
        - "Bug"
        - "Style"
        - "Documentation"
        - "Build"
        - "Refactor/Chore"
      placeholder: "ì„ íƒí•´ì£¼ì„¸ìš”"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "ğŸ“„ ì„¤ëª…"
      description: "ì´ìŠˆì— ëŒ€í•œ ì„¤ëª…ì„ ì‘ì„±í•´ì£¼ì„¸ìš”."
      placeholder: "ìì„¸íˆ ì ì„ìˆ˜ë¡ ì¢‹ìŠµë‹ˆë‹¤!"
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: "âœ… ì‘ì—…í•  ë‚´ìš©"
      description: "ì´ìŠˆ í•´ê²°ì„ ìœ„í•œ ì‘ì—… í•­ëª©ì„ ì²´í¬í•´ì£¼ì„¸ìš”."
      options:
        - "ì‘ì—…1"
        - "ì‘ì—…2"
        - "ì‘ì—…3"
      placeholder: "ìµœëŒ€í•œ ì„¸ë¶„í™” í•´ì„œ ì ì–´ì£¼ì„¸ìš”!"
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "ğŸ™‹ğŸ» ì°¸ê³  ìë£Œ"
      description: "ê´€ë ¨ ìë£Œë‚˜ ë§í¬ê°€ ìˆë‹¤ë©´ ì‘ì„±í•´ì£¼ì„¸ìš”."
      placeholder: "ë¬¸ì„œ, ë§í¬, ì´ë¯¸ì§€ ë“±"
    validations:
      required: false
